# Generated by Django 5.2 on 2025-06-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_shop', '0004_alter_carchoice_car_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarChoice',
        ),
    ]
