# Generated by Django 5.2 on 2025-06-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1_shop', '0009_delete_carchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_choice', models.CharField(choices=[('دنا', '620,000,000 T : دنا'), ('دنا پلاس', '720,500,000 T : دنا پلاس'), ('دنا پلاس توربو', '765,000,000 T : دنا پلاس توربو'), ('دنا پلاس توربو اتوماتیک', '1,150,000,000 T : دناپلاس توربو اتوماتیک'), ('سمند', '560,000,000 T : سمند'), ('سمند سورن', '520,000,000 T : سمند سورن'), ('سمند سورن پلاس', '760,000,000 T : سمند سورن پلاس'), ('پژو 405 XU7', '400,000,000 T : پژو 405 ایکس یو سون'), ('پژو 405 TU5', '650,000,000 T : پژو 405 تیو فایو'), ('پژو پارس XU7', '490,000,000 T : پژو پارس ایکس یو سون'), ('پژو پارس TU5', '900,000,000 T : پژو پارس تیو فایو'), ('پژو 206 TU5', '500,000,000 T : پژو 206 تیو فایو'), ('پژو 207 TU5', '623,555,000 T : پژو 207 تیو فایو'), ('رانا', '525,000,000 T : رانا'), ('رانا پلاس', '630,000,000 T : رانا پلاس'), ('تارا V1 plus', '940,000,000 T : تارا وی یک پلاس'), ('تارا V4', '1,120,000,000 T : تارا وی فور')], default='1', max_length=300, verbose_name='انتخاب خودرو')),
                ('color_choice', models.CharField(choices=[('مشکی', 'مشکی'), ('قرمز', 'قرمز'), ('سرمه ای', 'سرمه ای'), ('سفید', 'سفید'), ('یشمی', 'یشمی'), ('آبی', 'آبی'), ('مسی', 'مسی'), ('نقره ای', 'نقره ای'), ('خاکستری', 'خاکستری'), ('تیتانیومی', 'تیتانیومی'), ('فیلی', 'فیلی')], default='مشکی', max_length=300, verbose_name='رنگ')),
                ('many_car', models.IntegerField(default=1, verbose_name='تعداد')),
            ],
            options={
                'db_table': 'shopcar',
            },
        ),
    ]
