# Generated by Django 5.2 on 2025-06-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_shop', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarChoice',
        ),
    ]
