services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./Car_Shopping:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DJANGO_SETTINGS_MODULE=Car_shop.settings
    command: gunicorn --bind 0.0.0.0:8000 Car_shop.wsgi:application