# Generated by Django 5.2 on 2025-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_shop', '0009_alter_car_choice_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_choice',
            name='color_choice',
            field=models.CharField(choices=[('1', 'مشکی'), ('2', 'قرمز'), ('3', 'سرمه ای'), ('4', 'سفید'), ('5', 'یشمی'), ('6', 'آبی'), ('7', 'مسی'), ('8', 'نقره ای'), ('9', 'خاکستری'), ('10', 'تیتانیومی'), ('11', 'فیلی')], default='مشکی', max_length=300, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='car_choice',
            name='Car_choice',
            field=models.CharField(choices=[('1', 'دنا'), ('2', 'دنا پلاس'), ('3', 'دنا پلاس توربو'), ('4', 'دناپلاس توربو اتوماتیک'), ('5', 'سمند'), ('6', 'سمند سورن'), ('7', 'سمند سورن پلاس'), ('8', 'پژو 405 ایکس یو سون'), ('9', 'پژو 405 تیو فایو'), ('10', 'پژو پارس ایکس یو سون'), ('11', 'پژو پارس تیو فایو'), ('12', 'پژو 206 تیو فایو'), ('13', 'پژو 207 تیو فایو'), ('14', 'رانا'), ('15', 'رانا پلاس'), ('16', 'تارا وی یک پلاس'), ('17', 'تارا وی فور')], default='Dena', max_length=300, verbose_name='انتخاب خودرو'),
        ),
    ]
