# Generated by Django 5.2 on 2025-05-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_shop', '0012_alter_car_choice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car_choice',
            table='Select car',
        ),
    ]
