# Generated by Django 5.2 on 2025-05-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_shop', '0013_alter_car_choice_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car_Choice',
        ),
    ]
