# Generated by Django 5.2 on 2025-05-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'لیست قیمت',
            },
        ),
        migrations.AlterField(
            model_name='carchoice',
            name='many_car',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
