# Generated by Django 5.2 on 2025-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_shop', '0002_listprice_alter_carchoice_many_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListPrice',
        ),
        migrations.AlterField(
            model_name='carchoice',
            name='car_choice',
            field=models.CharField(choices=[('1', 'دنا : 620,000,000 T'), ('2', 'دنا پلاس : 720,500,000 T'), ('3', 'دنا پلاس توربو : 765,000,000 T'), ('4', 'دناپلاس توربو اتوماتیک : 1,150,000,000 T'), ('5', 'سمند : 560,000,000 T'), ('6', 'سمند سورن : 520,000,000'), ('7', 'سمند سورن پلاس : 760,000,000 T'), ('8', 'پژو 405 ایکس یو سون : 400,000,000 T'), ('9', 'پژو 405 تیو فایو : 650,000,000 T'), ('10', 'پژو پارس ایکس یو سون : 490,000,000 T'), ('11', 'پژو پارس تیو فایو : 900,000,000 T'), ('12', 'پژو 206 تیو فایو : 500,000,000 T'), ('13', 'پژو 207 تیو فایو : 623,555,000 T'), ('14', 'رانا : 525,000,000 T'), ('15', 'رانا پلاس : 630,000,000 T'), ('16', 'تارا وی یک پلاس : 940,000,000 T'), ('17', 'تارا وی فور : 1,120,000,000 T')], default='دنا', max_length=300, verbose_name='انتخاب خودرو'),
        ),
    ]
