# Generated by Django 5.2 on 2025-06-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_shop', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarChoice',
        ),
    ]
