# Generated by Django 5.2 on 2025-05-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_shop', '0002_alter_car_choice_car_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_choice',
            name='Car_many',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='car_choice',
            name='Car_choice',
            field=models.CharField(choices=[('1', 'Dena'), ('2', 'Dena plus'), ('3', 'Dena plus turbo'), ('4', 'Dena plus turbo automat'), ('5', 'Samand'), ('6', 'Samand Soren'), ('7', 'Samand Soren plus'), ('8', 'Peugeot 405 XU7'), ('9', 'Peugeot 405 TU5'), ('10', 'Peugeot pars XU7'), ('11', 'Peugeot pars TU5'), ('12', 'Peugeot 206 TU5'), ('13', 'Peugeot 207 TU5'), ('14', 'Rana'), ('15', 'Rana plus'), ('16', 'Tara V1 plus'), ('17', 'Tara V4')], default='Dena', max_length=300, verbose_name='اتومبیل خود را انتخاب نمایید'),
        ),
    ]
