# Generated by Django 5.2 on 2025-05-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_shop', '0003_car_choice_car_many_alter_car_choice_car_choice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car_choice',
            table='Selectyourcar',
        ),
    ]
