# Generated by Django 5.2 on 2025-05-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_shop', '0005_alter_car_choice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car_choice',
            table='select your car',
        ),
    ]
