# Generated by Django 5.2 on 2025-05-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_shop', '0008_car_choice_delete_todo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car_choice',
            table='Select your car',
        ),
    ]
