# Generated by Django 5.2 on 2025-05-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_shop', '0010_car_choice_color_choice_alter_car_choice_car_choice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car_choice',
            table='Select car',
        ),
    ]
